USE [master]
GO

/****** Object:  Database [TrueOrFalse]    Script Date: 09/15/2008 17:10:08 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'TrueOrFalse')
DROP DATABASE [TrueOrFalse]
GO

USE [master]
GO

/****** Object:  Database [TrueOrFalse]    Script Date: 09/15/2008 17:10:08 ******/
CREATE DATABASE [TrueOrFalse] ON  PRIMARY 
( NAME = N'TrueOrFalse', FILENAME = N'C:\Programme\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\TrueOrFalse.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TrueOrFalse_log', FILENAME = N'C:\Programme\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\TrueOrFalse_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TrueOrFalse] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TrueOrFalse].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TrueOrFalse] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TrueOrFalse] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TrueOrFalse] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TrueOrFalse] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TrueOrFalse] SET ARITHABORT OFF 
GO

ALTER DATABASE [TrueOrFalse] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TrueOrFalse] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TrueOrFalse] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TrueOrFalse] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TrueOrFalse] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TrueOrFalse] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TrueOrFalse] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TrueOrFalse] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TrueOrFalse] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TrueOrFalse] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TrueOrFalse] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TrueOrFalse] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TrueOrFalse] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TrueOrFalse] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TrueOrFalse] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TrueOrFalse] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TrueOrFalse] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TrueOrFalse] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TrueOrFalse] SET  READ_WRITE 
GO

ALTER DATABASE [TrueOrFalse] SET RECOVERY FULL 
GO

ALTER DATABASE [TrueOrFalse] SET  MULTI_USER 
GO

ALTER DATABASE [TrueOrFalse] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TrueOrFalse] SET DB_CHAINING OFF 
GO



USE [TrueOrFalse]
GO

/****** Object:  Table [dbo].[Question]    Script Date: 09/15/2008 17:09:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Question](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Text] [varchar](8000) NOT NULL,
	[Answer_Value] [varchar](1000) NOT NULL,
	[Source_Name] [varchar](8000) NOT NULL,
	[Source_Url] [varchar](1000) NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
 CONSTRAINT [PK_Question] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO